version: '3'

services:
  kali-service:
    build: 
        context: .
        dockerfile: toolkali
    image: "kalicmd/latest"
    volumes:
      - /mnt/share-kali:/share
      - /mnt/share-kali/.bash_history:/root/.bash_history
