name: "kali docker compose CI workflow"


on:
  push:
    branches: [ main ]
  schedule:
      - cron:  '0 0 1 * *' ##execution of a task in the first minute of the month     

jobs:

  ubuntu-latest-job:
    name: "kali-tools-forensics ubuntu latest"
    runs-on: ubuntu-latest
    env:
      distribution: "kalilinux" #https://hub.docker.com/r/kalilinux/kali-rolling
      version: "latest"
      name: "kali/kali-tools-forensics"
      dockerfiledir: "dockerfiles/kalilinux"
      dockerfilename: "toolkali"
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: |
        hostnamectl status
        lsb_release -a
        lsb_release -d
        cat /etc/lsb-release
        cat /etc/issue
        cat /etc/os-release
        sudo apt-get install -y neofetch && neofetch   
    - name: "docker build kali linux"
      run: |
        sudo mkdir /mnt/share-kali
        docker-compose --version
        sudo docker-compose --file dockerfiles/kalilinux/docker-compose-kali.yml up -d
        sudo docker-compose --file dockerfiles/kalilinux/docker-compose-kali.yml ps




